### ISSUE TITLE
Track selection in source file

### ISSUE THREAD

**Issue by RomanKhv** [joaoasrosa/nppxmltreeview#15]
Tree view should track current selection in source xml file (corresponding tree node should be highlited).

The same idea works fine user selects some node it the view - the cursor is moved to correspondint text in text editor. But unfortunately it doesn't work in opposite direction.

Really looking forward

Roman

**Comment by joaoasrosa** [comment]
Done as part of the Paris release. If any issue arises, let me know. Thanks

**Comment by RomanKhv** [comment]
How do I get the latest version?

**Comment by joaoasrosa** [comment]
Hi @RomanKhv,
The Notepad++ Plugin Manager Site is experiencing some problems. If you want to update it now you can follow the instructions at https://github.com/joaoasrosa/nppxmltreeview/wiki

Any problem let me know.

Cheers
