### ISSUE TITLE
BIG BUG in latest 1.4.0.45. release

### ISSUE THREAD

**Issue by mikhoul** [joaoasrosa/nppxmltreeview#19]
The **NppXMLTreeviewPlugin.zip** here: https://github.com/joaoasrosa/nppxmltreeview/releases/download/Paris-v1.4.0.45/NppXMLTreeviewPlugin.zip  and here https://github.com/joaoasrosa/nppxmltreeview/releases

It's "stamped" as the **version  1.3.0.45** instead of **version 1.4.0.45**:  http://i.imgur.com/t7O9Ots.png

It cause the plugin manager to goes **in a loop** and always want to update since the version number is wrong: http://i.imgur.com/dLWFEFo.png

Regards ! :octocat:

**Comment by joaoasrosa** [comment]
Hi,
Thanks for pointing that out.
Publish a new version (https://github.com/joaoasrosa/nppxmltreeview/releases/tag/London-v1.5.0.51), and cross checks with the DLL version.
The plugin manager site is down, waiting until it is up to update the references.
Regards!
