### ISSUE TITLE
could you share how to install is plugin?

### ISSUE THREAD

**Issue by whitemalt** [joaoasrosa/nppxmltreeview#21]
is plugin seem interesting , but I'm beginner user. I don't know how to install plugin to my notepad ++
or this project can't use anymore?

thanks you

**Comment by joaoasrosa** [comment]
Hi @noppadet008,

You can refer to https://github.com/joaoasrosa/nppxmltreeview/wiki.

Please let me know if that helps.

Cheers

**Comment by whitemalt** [comment]
thx for very fast reply

yes it help. thank you
but for additional comment you should add wiki link in readme.md because I didn't notice you has wiki on this project
and in wiki should edit this
> Use the Notepad++ Plugin Manager. Search for the XML Treeview plugin.

to something like this

> Use the Notepad++ Plugin Manager.  Search plugin name "Npp Xml Treeview"

because in plugin manager show that name 

Cheers,

**Comment by joaoasrosa** [comment]
Hi,

I will update it once I arrive to my machine.

Thanks for the enhancement.

Cheers

**Comment by joaoasrosa** [comment]
@noppadet008 it's done! Thanks for your contribution.
