### ISSUE TITLE
Repeat of issue 19

### ISSUE THREAD

**Issue by royalh13** [joaoasrosa/nppxmltreeview#26]
https://github.com/joaoasrosa/nppxmltreeview/issues/19,

latest versions of x86 dll details still show as 1.5.0.54 instead of 1.6.0.54.

causes plugin manager to continually mark as needing to be updated.

using plugin manager v1.4.9 & NPP v7.5.4

**Comment by joaoasrosa** [comment]
Hi,
It's my bad as maintainer of the repo. I will address it today, fixing this mismatch of versions.
Thanks for your support

**Comment by joaoasrosa** [comment]
Releasing a new version at the time.
Enhanced the build process, which causes the problem.
Closing the issue for the release.
Thanks for the support!
