### ISSUE TITLE
v1.6.0.54 download file is v1.5.x

### ISSUE THREAD

**Issue by nijawang** [joaoasrosa/nppxmltreeview#27]
The "NppTreeViewPlugin Berlin v1.6.0.54" download file (NppXMLTreeviewPlugin_x64) is v1.5.x, not v1.6.x.
Please correct it.
Thank you.

**Comment by fz0000** [comment]
The last London version is v1.5.x. I suppose that this Berlin version should be v1.6.x. So I think it's the file version info that is incorrect.
Hope it could be fixed asap. (Currently I just modified the file version locally to skip the update reminder :-) )

**Comment by flotux2** [comment]
Any news about the version mismatch? 

It is a bit annoying to see always that an update is available that cannot be installed. :-(

**Comment by joaoasrosa** [comment]
Hi all,
It's my bad as maintainer of the repo. I will address it today, fixing this mismatch of versions.
Thanks for your support

**Comment by flotux2** [comment]
Great, thanks!

**Comment by joaoasrosa** [comment]
Releasing a new version at the time.
Enhanced the build process, which causes the problem.
Closing the issue for the release.
Thanks for the support!
