### ISSUE TITLE
Toolbar option - HowTo

### ISSUE THREAD

**Issue by gaabne** [joaoasrosa/nppxmltreeview#29]
I see in enhancement of december 2016 for a Toolbar button

> Toolbar button should open tree view. This would be very handy.

>Hi @RomanKhv,
The enhancement is present in commit 20802bc and will be part of the next release.

What shall I do to get this Toolbar button ?

Same question for this one, also implemented, but not working for me 
- NotePad ++ x64 7.5.5
- Berlin version of TreeView (v 1.6.0.54 here, but 1.5.0.54 on About Box...)

> It would also be handy if the plugin would highlight appropriate tree node after clicking in the XML body ("follow the cursor").

Thanks

Gérard

**Comment by joaoasrosa** [comment]
Releasing a new version at the time.
Enhanced the build process, which causes the problem.
Closing the issue for the release.
Thanks for the support!

**Comment by gaabne** [comment]
Works fine - thanks for the update 

Gérard
