### ISSUE TITLE
Npp Xml Treeview keeps appearing with the same version after update: could it be a minor version and build number error, perhaps?

### ISSUE THREAD

**Issue by cmfaustino** [joaoasrosa/nppxmltreeview#30]
Hello, @joaoasrosa .
As the following screenshot of Notepad++ Plugin Manager shows,
the minor version is different (1.5 installed, 1.6 is the new version),
but the build number (0.54) is the same.
By any chance, is there a typo error in some file regarding the version,
that makes the Plugin Manager think that there is a new version "1.6",
when in fact, after updating, the version still remains at 1.5?
(Because this is what's happening to me: the installed version remains at 1.5, even after I did the update)
Thanks, in advance.

![npp_xml_treeview_minor_version_and_build_error_perhaps](https://user-images.githubusercontent.com/766254/37464124-5892f37e-284f-11e8-9b2f-62917ee23637.jpg)

**Comment by StevenBonePgh** [comment]
The 64 bit dll file version is 1.5.0.54 but the version listed in the update manifest is 1.6.0.54.  This is why it looks like there is still an update, even though you have the current version.

**Comment by joaoasrosa** [comment]
Hi all,
It's my bad as maintainer of the repo. I will address it today, fixing this mismatch of versions.
Thanks for your support

**Comment by joaoasrosa** [comment]
Releasing a new version at the time.
Enhanced the build process, which causes the problem.
Closing the issue for the release.
Thanks for the support!

**Comment by cmfaustino** [comment]
So, now, 29th April 23:30, I tried to update the plugin, and the error still occurs.
I'm using Windows 7 Home Premium SP1 64-bit, and the rest is in the following images
(error, version of plugin manager, version of Notepad++)
![error_still](https://user-images.githubusercontent.com/766254/39411705-5ddb988c-4c07-11e8-8ff4-9f0a28bbca35.jpg)
![plugin_manager_version](https://user-images.githubusercontent.com/766254/39411707-6c2ff374-4c07-11e8-83dc-c4bd81e9f2cd.jpg)
![notepadplusplus_version](https://user-images.githubusercontent.com/766254/39411708-72af3124-4c07-11e8-969d-d6fd1bd9d29a.jpg)

**Comment by cmfaustino** [comment]
Meanwhile, I'm going to send a message to Notepad++'s author,
because a user should be able to remove an installed plugin
which appears in the Updates section of the Plugin Manager...
...As you can see in the screenshot, there is no button to remove the installation of the plugin
(to try and re-install it in a clean way, instead of updating it)

**Comment by cmfaustino** [comment]
Issue created in
Plugin Manager - Updates section tab without Remove button
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4464

**Comment by joaoasrosa** [comment]
Hi @cmfaustino 
During today I wasn't unable to update the plugin via Plugin Manager. Apparently, they didn't refresh the database.
Thanks for raising it with the authors of Notepad++.

**Comment by cmfaustino** [comment]
The plugin manager, it seems, is separate from notepad++, so, it is in a different repository:
https://github.com/bruderstein/nppPluginManager/issues/107

**Comment by chcg** [comment]
See pluginmanager issue. Should be solved with next PM plugin list update also for 32bit.
