### ISSUE TITLE
Bad positionning in Notepad++ when select an XML treeview node

### ISSUE THREAD

**Issue by JMC13** [joaoasrosa/nppxmltreeview#4]
Hi,
I just tried your plugin and i like it, a good idea to accelerate navigation in an XML file. I don't know if i correctly use the plugin or if it's not an available function, but I would like to display  the section wich correspond to the selected node in the XML Treeview ( I don't know if my english is correct enough to understand my issue !?). For the very first node I already have a shift between treview and Notepad++ section and at the end of the treeview it seems totaly lost !
Do you already worked on that ?
Thanks for your work.
JMC

**Comment by joaoasrosa** [comment]
Hi JMC
Thanks for the contact. Sorry for the later reply.
There is a feature implemented to work in that way. If you click in the node (treeview) it should highlight it in the text editor.
This is what you try to do?
If do not work, can you send the XML file and the Notepad++ version?
Thanks

**Comment by radekbaranowski** [comment]
It would also be handy if the plugin would highlight appropriate tree node after clicking in the XML body ("follow the cursor").

**Comment by joaoasrosa** [comment]
Thanks for the input. Add as enhacement to the next release.

**Comment by joaoasrosa** [comment]
Hi,
This issue was resolved in the Dublin release.
Regards, João Rosa
