### ISSUE TITLE
"Collapse all" feature

### ISSUE THREAD

**Issue by radekbaranowski** [joaoasrosa/nppxmltreeview#5]
I opened v. large xml file and the tree expanded to the borders of unreadability. Is it possible to implement "collapse all" feature. Or maybe, if you could point me to the code part I could try to implement it myself.

**Comment by joaoasrosa** [comment]
By default the treeview is expanded. However for the given use case is not the best approach.
There are two routes:
- In the short term remove the option to expand the treeview (FormTreeView.cs, method ExpandTreeView)
- As a enhancement implement a button to toggle the expand/collapse tree view. This can be achieve adding a button to the top of the plugin as a toolbar.

Regards

(P.S. sorry for the delay, I was on my annual leave)

**Comment by joaoasrosa** [comment]
Hi,
This enhancement waas added in the Dublin release.
Regards, João Rosa
